import type { Metadata } from "next";
import "./globals.css";
import { AppSettingData } from "../config/app-data/appSetting";
import { BaseTemplate } from "../config/app-data/templates/base";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: `${AppSettingData.appName} - ${BaseTemplate.fullName} Portfolio`,
  description: `Generated by ${AppSettingData.appName}`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Toaster />
        {children}
      </body>
    </html>
  );
}
